### ISSUE TITLE
I tried installing sm64ex coop with this and got this error

### ISSUE THREAD

**Issue by dr34yt** [EmeraldLoc/sm_osx#22]
zsh:1: permission denied: /Users/(myname)/SM64Repos/sm64ex_coop-build/sm64.us.f3dex2e

**Comment by EmeraldLoc** [comment]
Yes this is known, please read the release page on the latest version of sm_osx. This will be fixed when the next version of sm64ex-coop comes out

**Comment by dr34yt** [comment]
problem is I don't know how to compile manually. and when I did the thing on the sm64ex coop for macOS arm it didn't work

**Comment by EmeraldLoc** [comment]
Download the repo from [here](https://github.com/djoslin0/sm64ex-coop), and unzip the folder, then follow the instructions on the issue page (specifically the Makefile part), then open up the terminal, run `cd ~/Downloads/sm64ex-coop` (or wherever you downloaded the sm64ex-coop stuff to, cd is just taking you to directories. fyi you can run `ls` to see the contents of that folder) then run `brew uninstall glew sdl2` then run `arch -x86_64 zsh` then your gonna wanna run the command that'll take the longest. If you want the fastest compilation speed (since your m1 it'll compile in roughly 5-8 minutes on fastest setting) run `gmake OSX_BUILD=1 USE_APP=0 -j` otherwise if you dont want the fastest, drop the -j, or run `gmake OSX_BUILD=1 USE_APP=0`. Then run `./build/us_pc/sm64.us.f3dex2e` to see if it launches, if it does, then head into finder, navigate to the sm64ex-coop folder, click the build folder, and copy the us_pc folder to the `SM64Repos` folder in the home directory, then go to sm_osx and select an already existing repo, and you will have sm64ex-coop in sm_osx, so you can create app shortcuts or whatever you wanna do.

**Comment by dr34yt** [comment]
which issue on the issue page

**Comment by dr34yt** [comment]
also im m2

**Comment by dr34yt** [comment]
I tried doing what you said and It didn't work

**Comment by EmeraldLoc** [comment]
i'll have to assist you later today, sorry about the late response, been busy for the past couple of days

**Comment by EmeraldLoc** [comment]
Ok, I hope this is pretty simple, now firstly, update sm_osx to the latest version (go to the settings of sm_osx, updates, check for updates). Then, go Add New Repo, and select the Custom repo. In the Clone URL section, put in 

"https://github.com/EmeraldLoc/sm64ex-coop-macos-fix"

Then your gonna wanna hit the "use x86_64" button, oh and set the name to sm64ex-coop. Then hit next, do what you want, compile, and that should work

**Comment by dr34yt** [comment]
I did it but I can't press the next button. am I missing something?

**Comment by EmeraldLoc** [comment]
OH, whoopsies, do "https://github.com/EmeraldLoc/sm64ex-coop-macos-fix.git" instead, forgot .git, my bad

**Comment by dr34yt** [comment]
THANK YOU IT WORKS!!1
